---
title: "Code for main figure"
author: "Anonymized for peer review (NC)"
reviewer: "Anonymized for peer review (JT)"
output: word_document
editor_options: 
  chunk_output_type: console
---
This code creates the main figure for the paper

```{r libraries}
# load libraries
library('tidyverse')
library('here')
library('geomtextpath')
library('grid')
library('gridExtra')

# specify directory
i_am('btmpact24e_figure.Rmd')

# set plotting theme
theme_set(theme_classic()) 

# turn off scientific notation
options(scipen = 999)
```

# Open combined data
```{r}
DF <- 
  readRDS('data/combined/DF.full.combined.Rds')
```

# Process data
```{r}
DF <- DF %>% 
  mutate(
    # identify year
    year = 
      substr(publication_date, 
             1, 
             4) %>% as.numeric(),
    
    # identify how much time has passed since event
    response_time = 
      if_else(dataset == 'ai',
              publication_date - as.Date("2022-11-30"), # when ChatGPT was released
              false  =
                if_else(dataset == "terror",
                        publication_date - as.Date("2001-09-11"), # date of 9/11 terrorist attacks
                        false = 
                          publication_date - as.Date("2020-03-11")) # when WHO declared pandemic
              ),
    response_time = as.numeric(response_time),
    
    # Transform the response_time variable into its opposite (speed) to improve visualization 
    speed = - response_time,
    
    # fix citation class
    cited_by_count = as.numeric(cited_by_count)
    ) %>%
  
  # remove instances that were published before the date
  filter(response_time > -1) %>% 
  
  # focus on first three years
  filter(response_time < (365*3)) %>% 
  
  # remove over n = 100 authors
  filter(authors.n < 100) %>% 
  
  # create authorship size bins (factor)
  mutate(size.bin = cut(authors.n,
                        breaks = c(-Inf, 4,
                                   9, 19, 
                                   29, 39, 
                                   49, 59, 
                                   69, 79, 
                                   89, 99, 
                                   Inf),
                        labels = c("1 - 4",
                                   "5 - 9",
                                   "10 - 19",
                                   "20 - 29",
                                   "30 - 39",
                                   "40 - 49",
                                   "50 - 59",
                                   "60 - 69",
                                   "70 - 79",
                                   "80 - 89",
                                   "90 - 99",
                                   "100 +")
                        )
         ) %>% 
  
  # calculate percentiles
  group_by(dataset) %>% 
  mutate(citation.per = percent_rank(cited_by_count) * 100,
         news.per = percent_rank(news) * 100,
         policy.per = percent_rank(policy) * 100,
         speed.per = percent_rank(speed) * 100) %>%
  ungroup()
```

Backup processed data
```{r}
saveRDS(DF,
        'data/combined/DF.full.combined.processed.Rds')

# DF <- readRDS('data/combined/DF.full.combined.processed.Rds')
```


# Create figure
## Calculate descriptives
```{r}
# calculate descriptives
desc <- DF %>% 
  group_by(dataset, size.bin) %>% 
  summarise(n = n(),
            
            m.cit = mean(citation.per, na.rm = T),
            sd.cit = sd(citation.per, na.rm = T),
            
            m.new = mean(news.per, na.rm = T),
            sd.new = sd(news.per, na.rm = T),
            
            m.pol = mean(policy.per, na.rm = T),
            sd.pol = sd(policy.per, na.rm = T),
            
            m.speed = mean(speed.per),
            sd.speed = sd(speed.per, na.rm = T))

# isolate COVID-19 descriptives and prepare for plotting
desc.c <- desc %>% 
  # isolate COVID-19 data
  filter(dataset == 'covid') %>% 
  
  # select relevant variables
  select(size.bin, m.cit, m.new, m.pol, m.speed) %>% 
  
  # pivot longer for plotting
  pivot_longer(m.cit : m.speed) %>% 
  
  # fix naming
  mutate(name = 
           case_when(name == "m.cit" ~ "scholarly article mentions",
                     name == "m.new" ~ "news output mentions",
                     name == "m.pol" ~ "policy document mentions",
                     name == "m.speed" ~ "response speed"
                     )
         )

# isolate ChatGPT descriptives
desc.a <- desc %>% 
  # isolate ChatGPT data
  filter(dataset == 'ai',
         n > 40) %>% 
  
  # select relevant variables
  select(size.bin, m.cit, m.new, m.pol, m.speed) %>% 
  
  # pivot longer for plotting
  pivot_longer(m.cit : m.speed) %>% 
  
  # fix naming
  mutate(name = 
           case_when(name == "m.cit" ~ "scholarly article mentions",
                     name == "m.new" ~ "news output mentions",
                     name == "m.pol" ~ "policy document mentions",
                     name == "m.speed" ~ "response speed"
                     )
         )

# isolate terrorism descriptives
desc.t <- desc %>% 
  # isolate ChatGPT data
  filter(dataset == 'terror',
         n > 75) %>% 
  
  # select relevant variables
  select(size.bin, m.cit, m.new, m.pol, m.speed) %>% 
  
  # pivot longer for plotting
  pivot_longer(m.cit : m.speed) %>% 
  
  # fix naming
  mutate(name = 
           case_when(name == "m.cit" ~ "scholarly article mentions",
                     name == "m.new" ~ "news output mentions",
                     name == "m.pol" ~ "policy document mentions",
                     name == "m.speed" ~ "response speed"
                     )
         )
```

## Plot terrorism data
```{r}
fig.t <- 
  ggplot(data = desc.t,
         aes(x = size.bin,
             y = value,
             color = name,
             group = name,
             fill = name,
             label = name)) +
  
  # raw data points and connecting line
  geom_point(alpha = .4) +
  geom_line(alpha = .4) +
  
  # smoothed line (with limits on number of knots to get line to fit)
  geom_smooth(method = 'gam',
              alpha = .1,
              size = .5,
              formula = y ~ s(x, k = 4)) +
  
  # improve aesthetics
  scale_fill_manual(values = c("#0072B2", "#D55E00", 
                               "#009E73", '#CC79A7')) +
  scale_color_manual(values = c("#0072B2", "#D55E00", 
                                "#009E73", '#CC79A7')) +
  
  labs(title = 'terrorism',
       y = "average percentile") +
  ylim(0, 74) +
  theme(axis.text.x = element_text(angle = 90, 
                                   hjust = 1,
                                   vjust = .5),
        axis.title.x = element_blank(),
        legend.position = 'none',
        plot.title = element_text(hjust = 0.5))
```


## Plot COVID-19 data
```{r}
fig.c <- 
  ggplot(data = desc.c,
       aes(x = size.bin,
           y = value,
           color = name,
           group = name,
           fill = name,
           label = name)) +
  
  # raw data points and connecting line
  geom_point(alpha = .4) +
  geom_line(alpha = .4) +
  
  # smoothed line
  geom_smooth(method = 'gam',
              alpha = .1,
              color = NA) +
  
  # annotate meaning of line (instead of creating legend)
  geom_textsmooth(method = 'gam',
                  vjust = -1.5,
                  size = 3) +
  
  # fix aesthetics
  scale_fill_manual(values = c("#0072B2", "#D55E00", 
                               "#009E73", '#CC79A7')) +
  scale_color_manual(values = c("#0072B2", "#D55E00", 
                                "#009E73", '#CC79A7')) +
  labs(title = 'COVID-19',
       y = "average percentile") +
  ylim(0, 74) +
  theme(axis.text.x = element_text(angle = 90, 
                                   hjust = 1,
                                   vjust = .5),
        axis.title = element_blank(),
        legend.position = 'none',
        plot.title = element_text(hjust = 0.5),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank())

#rm(desc.c)
```

## Plot ChatGPT data
Create labeled raw differences
```{r}
desc.a2 <- 
  DF %>% 
  
  # focus on comparing smallest and largest plotted team sizes
  filter(dataset == "ai",
         (size.bin == "1 - 4" | size.bin == "30 - 39")) %>% 
  
  # calculate summary statistics
  group_by(size.bin) %>% 
  summarise(m.cit = mean(cited_by_count, na.rm = T),
            m.new = mean(news, na.rm = T),
            m.pol = mean(policy, na.rm = T),
            m.speed = mean(speed)) %>% 
  select(size.bin, m.cit, m.new, m.pol, m.speed) %>% 
  
  # calculate mean difference between smallest and largest plotted team size 
  summarise("scholarly article mentions" = m.cit[1] - m.cit[2],
            "news output mentions" = m.new[1] - m.new[2],
            "policy document mentions" = m.pol[1] - m.pol[2],
            "response time" = m.speed[1] - m.speed[2]) %>% 
  
  # pivot longer for plotting
  pivot_longer("scholarly article mentions" : "response time",
               values_to = 'label') %>% 
  
  # improve label aesthetics
  mutate(label = abs(label) %>% 
           round(2),
         label = if_else(name == 'response time',
                         paste0(label, " days"),
                         paste0(label, " mentions")
                         )
         ) 

# connect label information to descriptives 
# this helps determine plotting positions
desc.a2 <- 
  desc.a %>% 
  
  # focus on starting and end point in label
  filter(size.bin == '1 - 4' |
           size.bin == '30 - 39') %>% 
  
  # pivot wider for plotting
  pivot_wider(names_from = size.bin,
              values_from = value) %>% 
  
  # improve names
  rename(y = '1 - 4',
         yend = '30 - 39') %>% 
  mutate(x = '1 - 4',
         xend = '30 - 39') %>% 
  
  # left join
  left_join(desc.a2,
            by = 'name')
```

Create plot
```{r}
fig.a <- 
  ggplot(data = desc.a,
         aes(x = size.bin,
             y = value,
             color = name,
             group = name,
             fill = name,
             label = name)) +
  
  # raw data points and connecting line
  geom_point(alpha = .4) +
  geom_line(alpha = .4) +
  
  # smoothed line (with limits on number of knots to get line to fit)
  geom_smooth(method = 'gam',
              alpha = .1,
              size = .5,
              formula = y ~ s(x, k = 4)) +
  
  # improve aesthetics
  scale_fill_manual(values = c("#0072B2", "#D55E00", 
                               "#009E73", '#CC79A7')) +
  scale_color_manual(values = c("#0072B2", "#D55E00", 
                                "#009E73", '#CC79A7')) +
  
  labs(title = 'ChatGPT',
       y = "average percentile") +
  ylim(0, 74) +
  theme(axis.text.x = element_text(angle = 90, 
                                   hjust = 1,
                                   vjust = .5),
        axis.title = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        legend.position = 'none',
        plot.title = element_text(hjust = 0.5))
```

##  Combine
```{r}
arrangeGrob(fig.t, fig.c, fig.a,
            ncol = 3,
            bottom = textGrob("# of co-authors",
                              gp = gpar(fontsize = 11)),
            widths = c(.34, .4, .26)) %>% 
  grid.draw()
```
