---
title: "Add noise to proprietary Altmetric data for public sharing"
author: "Anonymized for peer review (NC)"
reviewer: "Anonymized for peer review (JT)"
output: word_document
editor_options: 
  chunk_output_type: console
---
This code adds noise to proprietary Altmetric data for public sharing

# Load packages and settings
```{r set.env}
# load packages
library('tidyverse')
library('here')
library('readxl')
library('here')

# set seed for reproducibility
set.seed(1967)
```

# Raw data: Import and prep Altmetric data
## ChatGPT
```{r}
alt.cgpt <- 
  # open
  read.csv(here("data", 
                "cgpt", 
                "btmpact24e_altmetric_cgpt.csv")) %>% 
  
  # select relevant variables
  select(DOI, News.mentions, Blog.mentions, 
         Policy.mentions, X.mentions, Facebook.mentions)
```

## COVID-19
```{r}
alt.covid <-
  # open
  read.csv(here("data", 
                "covid", 
                "btmpact24e_altmetric_covid.csv")) %>% 
  
  # select relevant variables
  select(DOI, News.mentions, Blog.mentions, 
         Policy.mentions, X.mentions, Facebook.mentions)
```

## Terrorism
```{r}
alt.terror <-
  # open
  read.csv(here("data", 
                "terrorism", 
                "btmpact24e _altmetric_data_terrorism.csv")) %>% 
  
  # select relevant variables
  select(DOI, News.mentions, Blog.mentions, 
         Policy.mentions, X.mentions, Facebook.mentions)

```

# Raw data: Scramble, add random noise, and re-export Altmetric data
## ChatGPT
```{r}
alt.cgpt <-
  alt.cgpt %>% 
  
  # adds noise to each key outcome of the Chat GPT data set (randomly increases score by up to 10)  
  mutate(across(c("News.mentions", "Blog.mentions", 
                  "Policy.mentions",  "X.mentions", 
                  "Facebook.mentions"), 
                # randomly sample (sample) and add uniform noise (runif)
                ~ . + sample(0:10, size = nrow(alt.cgpt), 
                                    replace = TRUE)
                )
         )

# export
alt.cgpt %>% 
  write.csv(here("data", 
                 "cgpt", 
                 "btmpact24e_altmetric_cgpt_noise.csv"),
            row.names = F)
```

## COVID-19
```{r}
alt.covid <-
  alt.covid %>% 
  
  # adds noise to each key outcome of the COVID-19 data set (randomly increases score by up to 10)  
  mutate(across(c("News.mentions", "Blog.mentions", 
                  "Policy.mentions",  "X.mentions", 
                  "Facebook.mentions"), 
                # randomly sample (sample) and add noise (runif)
                ~ . + sample(0:10, size = nrow(alt.cgpt), 
                                    replace = TRUE)
                )
         )

# export
alt.covid %>% 
  write.csv(here("data", 
                 "covid", 
                 "btmpact24e_altmetric_covid_noise.csv"),
            row.names = F)
```

## Terrorism
```{r}
alt.terror <-
  alt.terror %>% 
  
  # adds noise to each key outcome of the terrorism data set (randomly increases score by up to 10)  
  mutate(across(c("News.mentions", "Blog.mentions", 
                  "Policy.mentions",  "X.mentions", 
                  "Facebook.mentions"), 
                # randomly sample (sample) and add uniform noise (runif)
                ~ . + sample(0:10, size = nrow(alt.cgpt), 
                                    replace = TRUE)
                )
         )

# export
alt.terror %>% 
  write.csv(here("data", 
                 "terrorism", 
                 "btmpact24e_altmetric_terror_noise.csv"),
            row.names = F)
```

```{r}
# remove raw data from environment
rm(alt.cgpt, alt.covid, alt.terror)
```

# Processed data: Import and prep datasets with Altmetric data
## DF.alt.combined.Rds
```{r}
# open
DF.alt.combined <-
  readRDS(here('data',
               'combined',
               'DF.alt.combined.Rds')
          ) 

# adds noise to each key outcome of the combined Altmetric data set (randomly increases score by up to 10) 
DF.alt.combined <- 
  DF.alt.combined %>% 
  mutate(across(c("News.mentions" : "Number.of.Dimensions.citations",
                  "news" : "policy"), 
                ~ . + sample(0:10, size = nrow(alt.cgpt), 
                                    replace = TRUE)
                )
         )

# re-export
DF.alt.combined %>% 
  saveRDS(here('data',
               'combined',
               'DF.alt.combined.noise.Rds'))

# remove
rm(DF.alt.combined)
```

## DF.full.combined.Rds
```{r}
# open
DF.full.combined <-
  readRDS(here('data',
               'combined',
               'DF.full.combined.Rds')
          ) 

# adds noise to each key outcome of the full combined data set (randomly increases score by up to 10) 
DF.full.combined <- 
  DF.full.combined %>% 
  mutate(across(c("News.mentions" : "Number.of.Dimensions.citations",
                  "news" : "policy"), 
                ~ sample(.) + runif(n = nrow(DF.full.combined), 
                                    max = 10)
                )
         )

# re-export
DF.full.combined %>% 
  saveRDS(here('data',
               'combined',
               'DF.full.combined.noise.Rds'))

rm(DF.full.combined)
```
