---
title: "Use OpenAlex API to compile papers with keyword terrorism"
author: "Anonymized for peer review (NC)"
reviewer: "Anonymized for peer review (JT)"
output: word_document
editor_options: 
  chunk_output_type: console
---

# Load packages and settings
```{r set.env}
# load packages
library('openalexR')
library('tidyverse')
library("jsonlite")

# specify API mailing key (if applicable)
# options(openalexR.mailto = "insert email here")
```

# Download records from API
```{r}
# download
DF <-
  oa_fetch(entity = "works",
           search = "terrorism",
           output = "list")

# convert from list to dataframe
DF2 <- works2df(DF)
```

# Export
```{r}
write_rds(DF2,"data/terrorism/btmpact24e_data_raw_terrorism.Rds")

DF2 <- readRDS('data/terrorism/btmpact24e_data_raw_terrorism.Rds')
```

# export DOI's for altmetric pull
```{r}
tmp <-DF2 %>% 
  # remove instances with no authorship info
  filter(!is.na(author)) %>% 

  # filter incomplete and duplicate records
  filter(!is.na(doi),
         doi != "") %>% 
  
  distinct(doi, 
           .keep_all = T) %>% 
  
  distinct(id, 
           .keep_all = T) %>% 
  
  # focus on records published after 2001-09-11
  mutate(publication_date = as.Date(publication_date)) %>% 
  filter(publication_date > "2001-09-11") %>% 
  
  # select variables of interest
  select(id, doi, title) %>% 
  
  arrange(desc(doi))

# export DOIs
write.csv("data/terrorism/btmpact24e_data_doi_terrorism.csv",
          row.names = F)
```
