---
title: "Use OpenAlex API to compile papers with keyword ChatGPT"
author: "Anonymized for peer review (NC)"
reviewer: "Anonymized for peer review (JT)"
output: word_document
editor_options: 
  chunk_output_type: console
---
This code fetches papers from the OpenAlex API using keyword ChatGPT.

# Setup
```{r set.env}
# specify data directory
data_dir <- Sys.getenv("data_dir")

# source setup file
source('setup.R')

# specify API mailing key (if applicable)
# options(openalexR.mailto = "insert email here")
```

# Download records from API
```{r download}
# download raw data
DF <- 
  oa_fetch(entity = "works",
           search = "ChatGPT",
           output = "list"
           )

# export raw data
saveRDS(DF,
        file.path(data_dir,
                  'cgpt',
                  'btmobile25a_data_raw_cgpt.Rds')
        )

# export binded data
DF <- DF %>% 
  works2df() 

DF %>% 
  saveRDS(
    file.path(data_dir,
              'cgpt',
              'btmobile25a_data_binded_cgpt.Rds')
          )
```

# Export DOI's for Altmetric pulls
```{r}
# select variables of interest
DF %>% 
  select(id, doi) %>%
  
  # filter complete records
  filter(doi != "") %>% 
  
  write.csv(
    file.path(data_dir,
              'cgpt',
              'btmobile25a_data_doi_cgpt.csv'),
    row.names = F)
```
