---
title: "Use OpenAlex API to compile papers with keyword COVID-19"
author: "Anonymized for peer review (NC)"
reviewer: "Anonymized for peer review (JT)"
output: word_document
editor_options: 
  chunk_output_type: console
---
This code fetches papers from the OpenAlex API using keyword COVID-19.

# Setup
```{r}
# specify data directory
data_dir <- Sys.getenv("data_dir")

# source setup file
source('setup.R')

# specify API mailing key (if applicable)
# options(openalexR.mailto = "insert email here")
```

# Download records from API
```{r download}
DF <- 
  oa_fetch(
    entity = "works",
    search = "COVID-19",
    output = "list",
    # note: limit variables using option to speed up API pull
    options = list(select = c('id', 'doi', 
                              'authorships', 'cited_by_count', 
                              'type'))
  )

# export raw data
DF %>% 
  saveRDS(file.path(data_dir,
                    'covid',
                    'btmobile25a_data_raw1_covid.Rds')
          )

# export binded data
DF <- DF %>% 
  works2df() 

DF %>% 
  saveRDS(file.path(data_dir,
                    'covid',
                    'btmobile25a_data_binded1_covid.Rds')
          )
```

# October 23 addition. Re-download records from API (because you missed the publication date)
```{r}
DF2 <- 
  oa_fetch(entity = "works",
           search = "COVID-19",
           output = "list",
           options = list(select = c('id', 'doi', 
                                     'authorships', 'cited_by_count', 
                                     'type', 'publication_date'))
           )

# export raw data
DF2 %>% 
  saveRDS(file.path(data_dir,
                    'covid',
                    'btmobile25a_data_raw2_covid.Rds')
          )

# export binded data
DF2 <- DF2 %>% 
  works2df() 

DF2 %>% 
  saveRDS(file.path(data_dir,
                    'covid',
                    'btmobile25a_data_binded2_covid.Rds')
          )
```

## October 30: Connect original COVID dataset with publication date from second API pull
Reload datasets (if necessary)
```{r eval = F}
DF <- 
  readRDS(file.path(data_dir,
                    'covid',
                    'btmobile25a_data_binded1_covid.Rds')
          )

DF2 <-
  readRDS(file.path(data_dir,
                    'covid',
                    'btmobile25a_data_binded2_covid.Rds')
          )

# select relevant variables
DF2 <- DF2 %>% 
  select(id, publication_date)
```

Merge, filter, and re-export
```{r}
DF.joined <- DF %>% 
  distinct(id, 
           .keep_all = T) %>% 
  left_join(.,
            DF2,
            by = "id")

# export
DF.joined %>% 
  saveRDS(file.path(data_dir,
                    'covid',
                    'btmobile25a_data_binded_covid.Rds')
          )

rm(DF, DF2)
```

# Export DOI's
```{r}
DF.joined %>%
  # select variables of interest
  select(doi, id) %>%   
  
  # filter complete records
  filter(doi != "")  %>% 
  
  write.csv(file.path(data_dir,
                      'covid',
                      'btmobile25a_data_doi_covid.csv'),
            row.names = F)
```
